apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "es2postgres.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "es2postgres.name" . }}
    helm.sh/chart: {{ include "es2postgres.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ddl.sql: |-
    {{- .Files.Get .Values.pg.ddl | nindent 4 }}
