apiVersion: v1
kind: Secret
metadata:
  name: {{ include "es2postgres.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "es2postgres.name" . }}
    helm.sh/chart: {{ include "es2postgres.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  pgPassword: {{ required "pg.password is required" .Values.pg.password | b64enc | quote }}
